name: swapit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  figma_squircle: ^0.5.3
  pinput: ^4.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  animate_do: ^3.3.4
  intl_phone_field: ^3.2.0
  country_picker:
  carousel_slider: ^4.2.1
  card_swiper: ^3.0.1
  dots_indicator: ^3.0.0
  shimmer: ^3.0.0
  animated_bottom_navigation_bar: ^1.3.3
  grouped_list: ^5.1.2
  device_info_plus:
  another_flushbar: ^1.12.30
  lottie:
  flutter_svg: ^2.0.10+1
  url_launcher:
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_charts:
  mrx_charts: ^0.1.3
  graphic: ^2.2.1
  permission_handler:
  marquee: ^2.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
#  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/icon/
    - assets/animation/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: Medium
      fonts:
        - asset: assets/font/Poppins-Medium.ttf
    - family: SemiBold
      fonts:
        - asset: assets/font/Poppins-SemiBold.ttf
    - family: Bold
      fonts:
        - asset: assets/font/Poppins-Bold.ttf

